# This workflow will test a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
name: Java Test with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'corretto'
        cache: maven
    - name: Maven Clean
      run: mvn clean
    - name: Maven Dependency
      run: mvn dependency
    - name: Test with Maven
      run: mvn test
